name: Clear Release Candidate
on:
  workflow_call:
    outputs:
      URL:
        value: ${{ jobs.clear-candidate.outputs.URL }}
        description: Link to the release candidate
  workflow_dispatch:

jobs:
  clear-candidate:
    name: Clear Release Candidate
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      URL: ${{ steps.clear.outputs.URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # We forcefully clone to retrieve the release_manager.py, so that it is available in consuming repositories
      - name: Check out code
        uses: actions/checkout@v4
        with:
          repository: "danielebra/simple-release-notes"
          path: simple-release-notes

      - name: Clear Candidate
        id: clear
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        shell: bash
        run: |
          set -e
          URL=$(python3 ./simple-release-notes/release_manager.py candidate clear)
          echo "URL=$URL" >> $GITHUB_OUTPUT
